modLoader="javafml" #mandatory

loaderVersion="[30,)" #mandatory (24 is current forge version)

credits="Thanks to Harry Talks for his amazing tutorials and Udemy for great Java courses." #optional

authors="kwpugh" #optional

[[mods]] #mandatory
modId="resourceful_tools" #mandatory
version="1.1.8" #mandatory
displayName="Resourceful Tools" #mandatory
description='''
A set of simple tools that allow you to obtain difficult to get resources
'''


[[dependencies.ring_of_miner]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[30,)" #mandatory
    ordering="NONE"
    side="BOTH"


# Here's another dependency
[[dependencies.ring_of_miner]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1]"
    ordering="NONE"
    side="BOTH"
